ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
export APP_NAME="Holiday Bot"
export TWITTER_CONSUMER_SECRET="get this value from app.twitter.com"
export TWITTER_CONSUMER_KEY="get this value from app.twitter.com"
export TWITTER_OAUTH_TOKEN="get this value from app.twitter.com"
export TWITTER_OAUTH_TOKEN_SECRET="get this value from app.twitter.com"
